default: &default
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>

production:
  <<: *default

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: <%= ENV["DB_NAME"] || 'client_demo' %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: <%= ENV["DB_NAME_TEST"] || 'client_demo_test' %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

# salesforce:
  # <<: *default
  # client_id: MVG9g9rbsTkKnAULfp4fzzy52o8.zkbvjUAsBQDSPa0WveWq502YVnCXjy.M0_Jbc8aWkE8paLB2VIjKVGr7   
  # client_secret: 7583119177831457562 
  # username: sheenagygax@getg5.com
  # password: M@gnu$09
  # security_token: mphUO7OdyGi84D526TL4jzjcw
  # objects: [Client]

